// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcR8CKcQtEXb7Dh69-ZillWNNYeYOQLn8',
    appId: '1:212719044790:android:8ccff6f25049e1c6e3fe17',
    messagingSenderId: '212719044790',
    projectId: 'mobile-apps-f671a',
    storageBucket: 'mobile-apps-f671a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmo7PXHeRxS1LEHHIDEq5FY9AzH7zlKVk',
    appId: '1:212719044790:ios:9f3c1e28cde80ff7e3fe17',
    messagingSenderId: '212719044790',
    projectId: 'mobile-apps-f671a',
    storageBucket: 'mobile-apps-f671a.appspot.com',
    androidClientId: '212719044790-42dv503u7ep5lbm0efrke34lclmm3brp.apps.googleusercontent.com',
    iosClientId: '212719044790-cc2hkb10uc6na3bj96ignkpq8617ndkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
